### ISSUE TITLE
Jiotv addon not working

### ISSUE THREAD

**Issue by ksadda77** [kiranreddyrebel/kiranreddyrebel.github.io#13]
Hi,
Jiotv addon is not working from yesterday. Only few news channels are working. Can you pls check & rectify?

**Comment by RaahgirTech** [comment]
Logout and re-login with your Jio mobile number and check.

**Comment by ksadda77** [comment]
Gr8. It worked. Thank you.

**Comment by ksadda77** [comment]
Closing as the issue is resolved after re-login.
