### ISSUE TITLE
22.0 alpha1 with kiran reddy plugin gives an error - 401 client error unauthorized for url ...etc

### ISSUE THREAD

**Issue by ranjeets9** [kiranreddyrebel/kiranreddyrebel.github.io#3]
22.0 alpha1 with kiran reddy plugin gives an error - 401 client error unauthorized for url ...etc

- Logged out and Logged in
-Reinstalled app 

same issue persists please check and advise 

Thank you in advance @kiranreddyrebel @tobalan @krreet

**Comment by ranjeets9** [comment]
same issue reported here as well https://github.com/krreet/plugin.video.jiotv/issues/135

**Comment by kiranreddyrebel** [comment]
Its sad to see this error. This jio dev's dont like to see us happy. :D lol,   thats why they keep on doing something with tv app. @ranjeets9

**Comment by ranjeets9** [comment]
> Its sad to see this error. This jio dev's dont like to see us happy. :D lol, thats why they keep on doing something with tv app. @ranjeets9

@kiranreddyrebel ya bro totally agreed any luck fixing or we wait?

**Comment by nabendu1** [comment]
@kiranreddyrebel  it seems something has changed in the header tokens . Based on my analysis till now seems that the requested headers are not correct due to user agent or some changes it expects 

    "inputstream.adaptive.stream_headers": urlencode(headers),
                    "inputstream.adaptive.manifest_headers": urlencode(headers),
                    "inputstream.adaptive.license_key
                    
 Nothing else seems to be wrong. 
 
 Not sure if the solution mentioned here is of any use https://forum.kodi.tv/archive/index.php?thread-373333.html

**Comment by xysterv** [comment]
Any luck with the updates.

**Comment by ranjeets9** [comment]
@krreet @tobalan @kiranreddyrebel still waiting for the updates bro?

**Comment by kiranreddyrebel** [comment]
@ranjeets9  Fixed error. Its working. Check it. Remove old one completely + also from kodi 's cache folder "packages" or else you can remove kodi and reinstall so that it doesn't get install plugin from cache folder.

**Comment by xysterv** [comment]
Where can i find the download link. The repo still shows old one

**Comment by ranjeets9** [comment]
> @ranjeets9 @xysterv Fixed error. Its working. Check it. Remove old one completely + also from kodi 's cache folder "packages" or else you can remove kodi and reinstall so that it doesn't get install plugin from cache folder.
> 
> @nabendu1 thanks , it was the culprit and fixed.
> 
> "Bool error" was due to ssl links are not getting fetch so changed method to urllib.request and disable ssl error.

Bro @kiranreddyrebel  need some more info should I stick with 20.5 and the same plugin? I had some errors posted already here https://github.com/kiranreddyrebel/kiranreddyrebel.github.io/issues/1

**Comment by kiranreddyrebel** [comment]
> > @ranjeets9 @xysterv Fixed error. Its working. Check it. Remove old one completely + also from kodi 's cache folder "packages" or else you can remove kodi and reinstall so that it doesn't get install plugin from cache folder.
> > 
> > @nabendu1 thanks , it was the culprit and fixed.
> > 
> > "Bool error" was due to ssl links are not getting fetch so changed method to urllib.request and disable ssl error.
> 
> Bro @kiranreddyrebel  need some more info should I stick with 20.5 and the same plugin? I had some errors posted already here https://github.com/kiranreddyrebel/kiranreddyrebel.github.io/issues/1

First uninstall jioplugin.
Clear cache of kodi app.
Then uninstall kodi.
Install latest kodi.
Follow same steps as earlier. Add source etc.

**Comment by ranjeets9** [comment]
> > > @ranjeets9 @xysterv Fixed error. Its working. Check it. Remove old one completely + also from kodi 's cache folder "packages" or else you can remove kodi and reinstall so that it doesn't get install plugin from cache folder.
> > > @nabendu1 thanks , it was the culprit and fixed.
> > > "Bool error" was due to ssl links are not getting fetch so changed method to urllib.request and disable ssl error.
> > 
> > 
> > Bro @kiranreddyrebel  need some more info should I stick with 20.5 and the same plugin? I had some errors posted already here #1
> 
> First uninstall jioplugin. Clear cache of kodi app. Then uninstall kodi. Install latest kodi. Follow same steps as earlier. Add source etc.

@kiranreddyrebel @nabendu1 Bro's thanks a lot I can confirm it is working super fine on both PC and Smart TV again thanks a lot for your help really appreciated 👍

**Comment by kiranreddyrebel** [comment]
@ranjeets9 

Bro, dont say thanks. Help the needy person and tell them to help other three. 

:D ;)

**Comment by xysterv** [comment]
Stopped working again
