### ISSUE TITLE
Jiotv 403 connection error

### ISSUE THREAD

**Issue by R3Conops** [kiranreddyrebel/kiranreddyrebel.github.io#7]
Epg list is not fully updating and since 4 am getting 403 connection error. on kodi 21 and addon updates off. @kiranreddyrebel

**Comment by KEERTHI1988-K2** [comment]
Not working, please give permanent solution

**Comment by A-d-i-t-h-y-a-n** [comment]
Same

**Comment by GTTech2305** [comment]
[jiotv+Rebel.zip](https://github.com/user-attachments/files/16430706/jiotv%2BRebel.zip)
Use this

**Comment by Arb-123** [comment]
Working👍

**Comment by Praveen-glich** [comment]
Working

**Comment by Tushari24** [comment]
How to install?

**Comment by SkieyeN** [comment]
Working, thank you. Except Sony channels not working.
@GTTech2305

**Comment by kiranreddyrebel** [comment]
> [jiotv+Rebel.zip](https://github.com/user-attachments/files/16430706/jiotv%2BRebel.zip)
> Use this it's same repo with some fix

Great work bro.

**Comment by kiranreddyrebel** [comment]
> [jiotv+Rebel.zip](https://github.com/user-attachments/files/16430706/jiotv%2BRebel.zip)
> Use this it's same repo with some fix

Also plz update about this zip in reddit post so that other can enjoy too. Lot of peoples are still pinging.. :)

**Comment by kiranreddyrebel** [comment]
Updated user-agent in utils.py with LYF jio phone and error is gone now. 

Such an headache with this. Lol.

**Comment by SkieyeN** [comment]
Sony channels not working with latest updated plugin

**Comment by ranjeets9** [comment]
> [jiotv+Rebel.zip](https://github.com/user-attachments/files/16430706/jiotv%2BRebel.zip) Use this it's same repo with some fix

@GTTech2305 Indeed it works thanks

**Comment by R3Conops** [comment]
> Epg list is not fully updating and since 4 am getting 403 connection error. on kodi 21 and addon updates off. @kiranreddyrebel

https://github.com/kiranreddyrebel/kiranreddyrebel.github.io/issues/7#issuecomment-2258714221
